// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.21.12
// source: rpc/proto/machines/coremachines/core_machine.v0.0.1.service.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StoreVersion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *StoreVersion) Reset() {
	*x = StoreVersion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreVersion) ProtoMessage() {}

func (x *StoreVersion) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreVersion.ProtoReflect.Descriptor instead.
func (*StoreVersion) Descriptor() ([]byte, []int) {
	return file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_rawDescGZIP(), []int{0}
}

func (x *StoreVersion) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type FetchEnvRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FetchEnvRequest) Reset() {
	*x = FetchEnvRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchEnvRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchEnvRequest) ProtoMessage() {}

func (x *FetchEnvRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchEnvRequest.ProtoReflect.Descriptor instead.
func (*FetchEnvRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_rawDescGZIP(), []int{1}
}

type FetchEnvResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	S3AccessKey string `protobuf:"bytes,1,opt,name=s3_access_key,json=s3AccessKey,proto3" json:"s3_access_key,omitempty"`
	S3SecretKey string `protobuf:"bytes,2,opt,name=s3_secret_key,json=s3SecretKey,proto3" json:"s3_secret_key,omitempty"`
}

func (x *FetchEnvResponse) Reset() {
	*x = FetchEnvResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchEnvResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchEnvResponse) ProtoMessage() {}

func (x *FetchEnvResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchEnvResponse.ProtoReflect.Descriptor instead.
func (*FetchEnvResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_rawDescGZIP(), []int{2}
}

func (x *FetchEnvResponse) GetS3AccessKey() string {
	if x != nil {
		return x.S3AccessKey
	}
	return ""
}

func (x *FetchEnvResponse) GetS3SecretKey() string {
	if x != nil {
		return x.S3SecretKey
	}
	return ""
}

type Plugin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PluginId int32  `protobuf:"varint,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Package  string `protobuf:"bytes,3,opt,name=package,proto3" json:"package,omitempty"`
}

func (x *Plugin) Reset() {
	*x = Plugin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Plugin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plugin) ProtoMessage() {}

func (x *Plugin) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plugin.ProtoReflect.Descriptor instead.
func (*Plugin) Descriptor() ([]byte, []int) {
	return file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_rawDescGZIP(), []int{3}
}

func (x *Plugin) GetPluginId() int32 {
	if x != nil {
		return x.PluginId
	}
	return 0
}

func (x *Plugin) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Plugin) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

type PluginRelease struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PluginReleaseId int32  `protobuf:"varint,1,opt,name=plugin_release_id,json=pluginReleaseId,proto3" json:"plugin_release_id,omitempty"`
	Major           int32  `protobuf:"varint,2,opt,name=major,proto3" json:"major,omitempty"`
	Minor           int32  `protobuf:"varint,3,opt,name=minor,proto3" json:"minor,omitempty"`
	Patch           int32  `protobuf:"varint,4,opt,name=patch,proto3" json:"patch,omitempty"`
	ZipFileUrl      string `protobuf:"bytes,5,opt,name=zip_file_url,json=zipFileUrl,proto3" json:"zip_file_url,omitempty"`
}

func (x *PluginRelease) Reset() {
	*x = PluginRelease{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PluginRelease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginRelease) ProtoMessage() {}

func (x *PluginRelease) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginRelease.ProtoReflect.Descriptor instead.
func (*PluginRelease) Descriptor() ([]byte, []int) {
	return file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_rawDescGZIP(), []int{4}
}

func (x *PluginRelease) GetPluginReleaseId() int32 {
	if x != nil {
		return x.PluginReleaseId
	}
	return 0
}

func (x *PluginRelease) GetMajor() int32 {
	if x != nil {
		return x.Major
	}
	return 0
}

func (x *PluginRelease) GetMinor() int32 {
	if x != nil {
		return x.Minor
	}
	return 0
}

func (x *PluginRelease) GetPatch() int32 {
	if x != nil {
		return x.Patch
	}
	return 0
}

func (x *PluginRelease) GetZipFileUrl() string {
	if x != nil {
		return x.ZipFileUrl
	}
	return ""
}

type FetchPluginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PluginId int32 `protobuf:"varint,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
}

func (x *FetchPluginRequest) Reset() {
	*x = FetchPluginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchPluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchPluginRequest) ProtoMessage() {}

func (x *FetchPluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchPluginRequest.ProtoReflect.Descriptor instead.
func (*FetchPluginRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_rawDescGZIP(), []int{5}
}

func (x *FetchPluginRequest) GetPluginId() int32 {
	if x != nil {
		return x.PluginId
	}
	return 0
}

type FetchPluginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Plugin       *Plugin          `protobuf:"bytes,1,opt,name=plugin,proto3" json:"plugin,omitempty"`
	Releases     []*PluginRelease `protobuf:"bytes,2,rep,name=releases,proto3" json:"releases,omitempty"`
	StoreVersion *StoreVersion    `protobuf:"bytes,3,opt,name=store_version,json=storeVersion,proto3" json:"store_version,omitempty"`
}

func (x *FetchPluginResponse) Reset() {
	*x = FetchPluginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchPluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchPluginResponse) ProtoMessage() {}

func (x *FetchPluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchPluginResponse.ProtoReflect.Descriptor instead.
func (*FetchPluginResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_rawDescGZIP(), []int{6}
}

func (x *FetchPluginResponse) GetPlugin() *Plugin {
	if x != nil {
		return x.Plugin
	}
	return nil
}

func (x *FetchPluginResponse) GetReleases() []*PluginRelease {
	if x != nil {
		return x.Releases
	}
	return nil
}

func (x *FetchPluginResponse) GetStoreVersion() *StoreVersion {
	if x != nil {
		return x.StoreVersion
	}
	return nil
}

type FetchPluginsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FetchPluginsRequest) Reset() {
	*x = FetchPluginsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchPluginsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchPluginsRequest) ProtoMessage() {}

func (x *FetchPluginsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchPluginsRequest.ProtoReflect.Descriptor instead.
func (*FetchPluginsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_rawDescGZIP(), []int{7}
}

type FetchPluginsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Plugins      []*Plugin     `protobuf:"bytes,1,rep,name=plugins,proto3" json:"plugins,omitempty"`
	StoreVersion *StoreVersion `protobuf:"bytes,2,opt,name=store_version,json=storeVersion,proto3" json:"store_version,omitempty"`
}

func (x *FetchPluginsResponse) Reset() {
	*x = FetchPluginsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchPluginsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchPluginsResponse) ProtoMessage() {}

func (x *FetchPluginsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchPluginsResponse.ProtoReflect.Descriptor instead.
func (*FetchPluginsResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_rawDescGZIP(), []int{8}
}

func (x *FetchPluginsResponse) GetPlugins() []*Plugin {
	if x != nil {
		return x.Plugins
	}
	return nil
}

func (x *FetchPluginsResponse) GetStoreVersion() *StoreVersion {
	if x != nil {
		return x.StoreVersion
	}
	return nil
}

type FetchLatestPluginReleaseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PluginReleaseId int32 `protobuf:"varint,1,opt,name=plugin_release_id,json=pluginReleaseId,proto3" json:"plugin_release_id,omitempty"`
}

func (x *FetchLatestPluginReleaseRequest) Reset() {
	*x = FetchLatestPluginReleaseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchLatestPluginReleaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchLatestPluginReleaseRequest) ProtoMessage() {}

func (x *FetchLatestPluginReleaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchLatestPluginReleaseRequest.ProtoReflect.Descriptor instead.
func (*FetchLatestPluginReleaseRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_rawDescGZIP(), []int{9}
}

func (x *FetchLatestPluginReleaseRequest) GetPluginReleaseId() int32 {
	if x != nil {
		return x.PluginReleaseId
	}
	return 0
}

type FetchLatestPluginReleaseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PluginRelease *PluginRelease `protobuf:"bytes,1,opt,name=plugin_release,json=pluginRelease,proto3" json:"plugin_release,omitempty"`
}

func (x *FetchLatestPluginReleaseResponse) Reset() {
	*x = FetchLatestPluginReleaseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchLatestPluginReleaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchLatestPluginReleaseResponse) ProtoMessage() {}

func (x *FetchLatestPluginReleaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchLatestPluginReleaseResponse.ProtoReflect.Descriptor instead.
func (*FetchLatestPluginReleaseResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_rawDescGZIP(), []int{10}
}

func (x *FetchLatestPluginReleaseResponse) GetPluginRelease() *PluginRelease {
	if x != nil {
		return x.PluginRelease
	}
	return nil
}

type FetchLatestCoreReleaseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FetchLatestCoreReleaseRequest) Reset() {
	*x = FetchLatestCoreReleaseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchLatestCoreReleaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchLatestCoreReleaseRequest) ProtoMessage() {}

func (x *FetchLatestCoreReleaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchLatestCoreReleaseRequest.ProtoReflect.Descriptor instead.
func (*FetchLatestCoreReleaseRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_rawDescGZIP(), []int{11}
}

type FetchLatestCoreReleaseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CoreReleaseId  int32  `protobuf:"varint,1,opt,name=core_release_id,json=coreReleaseId,proto3" json:"core_release_id,omitempty"`
	Major          int32  `protobuf:"varint,2,opt,name=major,proto3" json:"major,omitempty"`
	Minor          int32  `protobuf:"varint,3,opt,name=minor,proto3" json:"minor,omitempty"`
	Patch          int32  `protobuf:"varint,4,opt,name=patch,proto3" json:"patch,omitempty"`
	CoreZipFileUrl string `protobuf:"bytes,5,opt,name=core_zip_file_url,json=coreZipFileUrl,proto3" json:"core_zip_file_url,omitempty"`
	ArchBinFileUrl string `protobuf:"bytes,6,opt,name=arch_bin_file_url,json=archBinFileUrl,proto3" json:"arch_bin_file_url,omitempty"`
}

func (x *FetchLatestCoreReleaseResponse) Reset() {
	*x = FetchLatestCoreReleaseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchLatestCoreReleaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchLatestCoreReleaseResponse) ProtoMessage() {}

func (x *FetchLatestCoreReleaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchLatestCoreReleaseResponse.ProtoReflect.Descriptor instead.
func (*FetchLatestCoreReleaseResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_rawDescGZIP(), []int{12}
}

func (x *FetchLatestCoreReleaseResponse) GetCoreReleaseId() int32 {
	if x != nil {
		return x.CoreReleaseId
	}
	return 0
}

func (x *FetchLatestCoreReleaseResponse) GetMajor() int32 {
	if x != nil {
		return x.Major
	}
	return 0
}

func (x *FetchLatestCoreReleaseResponse) GetMinor() int32 {
	if x != nil {
		return x.Minor
	}
	return 0
}

func (x *FetchLatestCoreReleaseResponse) GetPatch() int32 {
	if x != nil {
		return x.Patch
	}
	return 0
}

func (x *FetchLatestCoreReleaseResponse) GetCoreZipFileUrl() string {
	if x != nil {
		return x.CoreZipFileUrl
	}
	return ""
}

func (x *FetchLatestCoreReleaseResponse) GetArchBinFileUrl() string {
	if x != nil {
		return x.ArchBinFileUrl
	}
	return ""
}

type FetchStoreInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FetchStoreInfoRequest) Reset() {
	*x = FetchStoreInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchStoreInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchStoreInfoRequest) ProtoMessage() {}

func (x *FetchStoreInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchStoreInfoRequest.ProtoReflect.Descriptor instead.
func (*FetchStoreInfoRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_rawDescGZIP(), []int{13}
}

type FetchStoreInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StoreVersion *StoreVersion `protobuf:"bytes,1,opt,name=store_version,json=storeVersion,proto3" json:"store_version,omitempty"`
}

func (x *FetchStoreInfoResponse) Reset() {
	*x = FetchStoreInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchStoreInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchStoreInfoResponse) ProtoMessage() {}

func (x *FetchStoreInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchStoreInfoResponse.ProtoReflect.Descriptor instead.
func (*FetchStoreInfoResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_rawDescGZIP(), []int{14}
}

func (x *FetchStoreInfoResponse) GetStoreVersion() *StoreVersion {
	if x != nil {
		return x.StoreVersion
	}
	return nil
}

type FetchPluginByPRIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PluginReleaseId int32 `protobuf:"varint,1,opt,name=plugin_release_id,json=pluginReleaseId,proto3" json:"plugin_release_id,omitempty"`
}

func (x *FetchPluginByPRIdRequest) Reset() {
	*x = FetchPluginByPRIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchPluginByPRIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchPluginByPRIdRequest) ProtoMessage() {}

func (x *FetchPluginByPRIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchPluginByPRIdRequest.ProtoReflect.Descriptor instead.
func (*FetchPluginByPRIdRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_rawDescGZIP(), []int{15}
}

func (x *FetchPluginByPRIdRequest) GetPluginReleaseId() int32 {
	if x != nil {
		return x.PluginReleaseId
	}
	return 0
}

type FetchPluginByPRIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Plugin *Plugin `protobuf:"bytes,1,opt,name=plugin,proto3" json:"plugin,omitempty"`
}

func (x *FetchPluginByPRIdResponse) Reset() {
	*x = FetchPluginByPRIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchPluginByPRIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchPluginByPRIdResponse) ProtoMessage() {}

func (x *FetchPluginByPRIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchPluginByPRIdResponse.ProtoReflect.Descriptor instead.
func (*FetchPluginByPRIdResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_rawDescGZIP(), []int{16}
}

func (x *FetchPluginByPRIdResponse) GetPlugin() *Plugin {
	if x != nil {
		return x.Plugin
	}
	return nil
}

var File_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto protoreflect.FileDescriptor

var file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_rawDesc = []byte{
	0x0a, 0x41, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x61, 0x63, 0x68,
	0x69, 0x6e, 0x65, 0x73, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65,
	0x73, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x2e, 0x76,
	0x30, 0x2e, 0x30, 0x2e, 0x31, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x1f, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d,
	0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x73, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x6d, 0x61, 0x63, 0x68,
	0x69, 0x6e, 0x65, 0x73, 0x22, 0x28, 0x0a, 0x0c, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x11,
	0x0a, 0x0f, 0x46, 0x65, 0x74, 0x63, 0x68, 0x45, 0x6e, 0x76, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x5a, 0x0a, 0x10, 0x46, 0x65, 0x74, 0x63, 0x68, 0x45, 0x6e, 0x76, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x0d, 0x73, 0x33, 0x5f, 0x61, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x33,
	0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4b, 0x65, 0x79, 0x12, 0x22, 0x0a, 0x0d, 0x73, 0x33, 0x5f,
	0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x73, 0x33, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x22, 0x53, 0x0a,
	0x06, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x6c, 0x75, 0x67,
	0x69, 0x6e, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x63, 0x6b,
	0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x63, 0x6b, 0x61,
	0x67, 0x65, 0x22, 0x9f, 0x01, 0x0a, 0x0d, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x6c,
	0x65, 0x61, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x11, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x5f, 0x72,
	0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x6d, 0x61, 0x6a, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x6d, 0x61, 0x6a, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x69, 0x6e, 0x6f, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x69, 0x6e, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05,
	0x70, 0x61, 0x74, 0x63, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x70, 0x61, 0x74,
	0x63, 0x68, 0x12, 0x20, 0x0a, 0x0c, 0x7a, 0x69, 0x70, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x75,
	0x72, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x7a, 0x69, 0x70, 0x46, 0x69, 0x6c,
	0x65, 0x55, 0x72, 0x6c, 0x22, 0x31, 0x0a, 0x12, 0x46, 0x65, 0x74, 0x63, 0x68, 0x50, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x49, 0x64, 0x22, 0xf6, 0x01, 0x0a, 0x13, 0x46, 0x65, 0x74, 0x63,
	0x68, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x3f, 0x0a, 0x06, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x27, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x61, 0x63, 0x68,
	0x69, 0x6e, 0x65, 0x73, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65,
	0x73, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x52, 0x06, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x12, 0x4a, 0x0a, 0x08, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d,
	0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x73, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x6d, 0x61, 0x63, 0x68,
	0x69, 0x6e, 0x65, 0x73, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x6c, 0x65, 0x61,
	0x73, 0x65, 0x52, 0x08, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x73, 0x12, 0x52, 0x0a, 0x0d,
	0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x73, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x6d, 0x61, 0x63,
	0x68, 0x69, 0x6e, 0x65, 0x73, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x52, 0x0c, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x22, 0x15, 0x0a, 0x13, 0x46, 0x65, 0x74, 0x63, 0x68, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xad, 0x01, 0x0a, 0x14, 0x46, 0x65, 0x74, 0x63,
	0x68, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x41, 0x0a, 0x07, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x27, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x61,
	0x63, 0x68, 0x69, 0x6e, 0x65, 0x73, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x6d, 0x61, 0x63, 0x68, 0x69,
	0x6e, 0x65, 0x73, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x52, 0x07, 0x70, 0x6c, 0x75, 0x67,
	0x69, 0x6e, 0x73, 0x12, 0x52, 0x0a, 0x0d, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x72, 0x70, 0x63,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x73, 0x2e,
	0x63, 0x6f, 0x72, 0x65, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x73, 0x2e, 0x53, 0x74, 0x6f,
	0x72, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x0c, 0x73, 0x74, 0x6f, 0x72, 0x65,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x4d, 0x0a, 0x1f, 0x46, 0x65, 0x74, 0x63, 0x68,
	0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x6c, 0x65,
	0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x11, 0x70, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x5f, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x6c,
	0x65, 0x61, 0x73, 0x65, 0x49, 0x64, 0x22, 0x79, 0x0a, 0x20, 0x46, 0x65, 0x74, 0x63, 0x68, 0x4c,
	0x61, 0x74, 0x65, 0x73, 0x74, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x6c, 0x65, 0x61,
	0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x55, 0x0a, 0x0e, 0x70, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x5f, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d,
	0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x73, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x6d, 0x61, 0x63, 0x68,
	0x69, 0x6e, 0x65, 0x73, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x6c, 0x65, 0x61,
	0x73, 0x65, 0x52, 0x0d, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73,
	0x65, 0x22, 0x1f, 0x0a, 0x1d, 0x46, 0x65, 0x74, 0x63, 0x68, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74,
	0x43, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0xe0, 0x01, 0x0a, 0x1e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x4c, 0x61, 0x74, 0x65,
	0x73, 0x74, 0x43, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x0f, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x72, 0x65,
	0x6c, 0x65, 0x61, 0x73, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d,
	0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x6d, 0x61, 0x6a, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x61,
	0x6a, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x69, 0x6e, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x6d, 0x69, 0x6e, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x61, 0x74,
	0x63, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x70, 0x61, 0x74, 0x63, 0x68, 0x12,
	0x29, 0x0a, 0x11, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x7a, 0x69, 0x70, 0x5f, 0x66, 0x69, 0x6c, 0x65,
	0x5f, 0x75, 0x72, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6f, 0x72, 0x65,
	0x5a, 0x69, 0x70, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x29, 0x0a, 0x11, 0x61, 0x72,
	0x63, 0x68, 0x5f, 0x62, 0x69, 0x6e, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x61, 0x72, 0x63, 0x68, 0x42, 0x69, 0x6e, 0x46, 0x69,
	0x6c, 0x65, 0x55, 0x72, 0x6c, 0x22, 0x17, 0x0a, 0x15, 0x46, 0x65, 0x74, 0x63, 0x68, 0x53, 0x74,
	0x6f, 0x72, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x6c,
	0x0a, 0x16, 0x46, 0x65, 0x74, 0x63, 0x68, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x52, 0x0a, 0x0d, 0x73, 0x74, 0x6f, 0x72,
	0x65, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x2d, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x61, 0x63, 0x68,
	0x69, 0x6e, 0x65, 0x73, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65,
	0x73, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x0c,
	0x73, 0x74, 0x6f, 0x72, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x46, 0x0a, 0x18,
	0x46, 0x65, 0x74, 0x63, 0x68, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x42, 0x79, 0x50, 0x52, 0x49,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x11, 0x70, 0x6c, 0x75, 0x67,
	0x69, 0x6e, 0x5f, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x6c, 0x65, 0x61,
	0x73, 0x65, 0x49, 0x64, 0x22, 0x5c, 0x0a, 0x19, 0x46, 0x65, 0x74, 0x63, 0x68, 0x50, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x42, 0x79, 0x50, 0x52, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x3f, 0x0a, 0x06, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x27, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x61,
	0x63, 0x68, 0x69, 0x6e, 0x65, 0x73, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x6d, 0x61, 0x63, 0x68, 0x69,
	0x6e, 0x65, 0x73, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x52, 0x06, 0x70, 0x6c, 0x75, 0x67,
	0x69, 0x6e, 0x32, 0xcb, 0x07, 0x0a, 0x12, 0x43, 0x6f, 0x72, 0x65, 0x4d, 0x61, 0x63, 0x68, 0x69,
	0x6e, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x6f, 0x0a, 0x08, 0x46, 0x65, 0x74,
	0x63, 0x68, 0x45, 0x6e, 0x76, 0x12, 0x30, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x73, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x6d,
	0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x73, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x45, 0x6e, 0x76,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x31, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x73, 0x2e, 0x63, 0x6f, 0x72,
	0x65, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x73, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x45,
	0x6e, 0x76, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x78, 0x0a, 0x0b, 0x46, 0x65,
	0x74, 0x63, 0x68, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x12, 0x33, 0x2e, 0x72, 0x70, 0x63, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x73, 0x2e, 0x63,
	0x6f, 0x72, 0x65, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x73, 0x2e, 0x46, 0x65, 0x74, 0x63,
	0x68, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x34,
	0x2e, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69,
	0x6e, 0x65, 0x73, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x73,
	0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x7b, 0x0a, 0x0c, 0x46, 0x65, 0x74, 0x63, 0x68, 0x50, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x73, 0x12, 0x34, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x73, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x6d, 0x61,
	0x63, 0x68, 0x69, 0x6e, 0x65, 0x73, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x50, 0x6c, 0x75, 0x67,
	0x69, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x35, 0x2e, 0x72, 0x70, 0x63,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x73, 0x2e,
	0x63, 0x6f, 0x72, 0x65, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x73, 0x2e, 0x46, 0x65, 0x74,
	0x63, 0x68, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x9f, 0x01, 0x0a, 0x18, 0x46, 0x65, 0x74, 0x63, 0x68, 0x4c, 0x61, 0x74, 0x65, 0x73,
	0x74, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x12, 0x40,
	0x2e, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69,
	0x6e, 0x65, 0x73, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x73,
	0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x50, 0x6c, 0x75, 0x67,
	0x69, 0x6e, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x41, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x61, 0x63,
	0x68, 0x69, 0x6e, 0x65, 0x73, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e,
	0x65, 0x73, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x50, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x99, 0x01, 0x0a, 0x16, 0x46, 0x65, 0x74, 0x63, 0x68, 0x4c, 0x61, 0x74,
	0x65, 0x73, 0x74, 0x43, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x12, 0x3e,
	0x2e, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69,
	0x6e, 0x65, 0x73, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x73,
	0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x43, 0x6f, 0x72, 0x65,
	0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x3f,
	0x2e, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69,
	0x6e, 0x65, 0x73, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x73,
	0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x43, 0x6f, 0x72, 0x65,
	0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x8a, 0x01, 0x0a, 0x11, 0x46, 0x65, 0x74, 0x63, 0x68, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x42,
	0x79, 0x50, 0x52, 0x49, 0x64, 0x12, 0x39, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x73, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x6d,
	0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x73, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x50, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x42, 0x79, 0x50, 0x52, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x3a, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x61, 0x63,
	0x68, 0x69, 0x6e, 0x65, 0x73, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e,
	0x65, 0x73, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x42, 0x79,
	0x50, 0x52, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x81, 0x01, 0x0a,
	0x0e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x36, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x61, 0x63, 0x68,
	0x69, 0x6e, 0x65, 0x73, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65,
	0x73, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x37, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x73, 0x2e, 0x63, 0x6f, 0x72,
	0x65, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x73, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x53,
	0x74, 0x6f, 0x72, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x22, 0x5a, 0x20, 0x72, 0x70, 0x63, 0x2f, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x73,
	0x2f, 0x63, 0x6f, 0x72, 0x65, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x73, 0x2f, 0x76, 0x30,
	0x5f, 0x30, 0x5f, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_rawDescOnce sync.Once
	file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_rawDescData = file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_rawDesc
)

func file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_rawDescGZIP() []byte {
	file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_rawDescOnce.Do(func() {
		file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_rawDescData)
	})
	return file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_rawDescData
}

var file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_goTypes = []interface{}{
	(*StoreVersion)(nil),                     // 0: rpc.proto.machines.coremachines.StoreVersion
	(*FetchEnvRequest)(nil),                  // 1: rpc.proto.machines.coremachines.FetchEnvRequest
	(*FetchEnvResponse)(nil),                 // 2: rpc.proto.machines.coremachines.FetchEnvResponse
	(*Plugin)(nil),                           // 3: rpc.proto.machines.coremachines.Plugin
	(*PluginRelease)(nil),                    // 4: rpc.proto.machines.coremachines.PluginRelease
	(*FetchPluginRequest)(nil),               // 5: rpc.proto.machines.coremachines.FetchPluginRequest
	(*FetchPluginResponse)(nil),              // 6: rpc.proto.machines.coremachines.FetchPluginResponse
	(*FetchPluginsRequest)(nil),              // 7: rpc.proto.machines.coremachines.FetchPluginsRequest
	(*FetchPluginsResponse)(nil),             // 8: rpc.proto.machines.coremachines.FetchPluginsResponse
	(*FetchLatestPluginReleaseRequest)(nil),  // 9: rpc.proto.machines.coremachines.FetchLatestPluginReleaseRequest
	(*FetchLatestPluginReleaseResponse)(nil), // 10: rpc.proto.machines.coremachines.FetchLatestPluginReleaseResponse
	(*FetchLatestCoreReleaseRequest)(nil),    // 11: rpc.proto.machines.coremachines.FetchLatestCoreReleaseRequest
	(*FetchLatestCoreReleaseResponse)(nil),   // 12: rpc.proto.machines.coremachines.FetchLatestCoreReleaseResponse
	(*FetchStoreInfoRequest)(nil),            // 13: rpc.proto.machines.coremachines.FetchStoreInfoRequest
	(*FetchStoreInfoResponse)(nil),           // 14: rpc.proto.machines.coremachines.FetchStoreInfoResponse
	(*FetchPluginByPRIdRequest)(nil),         // 15: rpc.proto.machines.coremachines.FetchPluginByPRIdRequest
	(*FetchPluginByPRIdResponse)(nil),        // 16: rpc.proto.machines.coremachines.FetchPluginByPRIdResponse
}
var file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_depIdxs = []int32{
	3,  // 0: rpc.proto.machines.coremachines.FetchPluginResponse.plugin:type_name -> rpc.proto.machines.coremachines.Plugin
	4,  // 1: rpc.proto.machines.coremachines.FetchPluginResponse.releases:type_name -> rpc.proto.machines.coremachines.PluginRelease
	0,  // 2: rpc.proto.machines.coremachines.FetchPluginResponse.store_version:type_name -> rpc.proto.machines.coremachines.StoreVersion
	3,  // 3: rpc.proto.machines.coremachines.FetchPluginsResponse.plugins:type_name -> rpc.proto.machines.coremachines.Plugin
	0,  // 4: rpc.proto.machines.coremachines.FetchPluginsResponse.store_version:type_name -> rpc.proto.machines.coremachines.StoreVersion
	4,  // 5: rpc.proto.machines.coremachines.FetchLatestPluginReleaseResponse.plugin_release:type_name -> rpc.proto.machines.coremachines.PluginRelease
	0,  // 6: rpc.proto.machines.coremachines.FetchStoreInfoResponse.store_version:type_name -> rpc.proto.machines.coremachines.StoreVersion
	3,  // 7: rpc.proto.machines.coremachines.FetchPluginByPRIdResponse.plugin:type_name -> rpc.proto.machines.coremachines.Plugin
	1,  // 8: rpc.proto.machines.coremachines.CoreMachineService.FetchEnv:input_type -> rpc.proto.machines.coremachines.FetchEnvRequest
	5,  // 9: rpc.proto.machines.coremachines.CoreMachineService.FetchPlugin:input_type -> rpc.proto.machines.coremachines.FetchPluginRequest
	7,  // 10: rpc.proto.machines.coremachines.CoreMachineService.FetchPlugins:input_type -> rpc.proto.machines.coremachines.FetchPluginsRequest
	9,  // 11: rpc.proto.machines.coremachines.CoreMachineService.FetchLatestPluginRelease:input_type -> rpc.proto.machines.coremachines.FetchLatestPluginReleaseRequest
	11, // 12: rpc.proto.machines.coremachines.CoreMachineService.FetchLatestCoreRelease:input_type -> rpc.proto.machines.coremachines.FetchLatestCoreReleaseRequest
	15, // 13: rpc.proto.machines.coremachines.CoreMachineService.FetchPluginByPRId:input_type -> rpc.proto.machines.coremachines.FetchPluginByPRIdRequest
	13, // 14: rpc.proto.machines.coremachines.CoreMachineService.FetchStoreInfo:input_type -> rpc.proto.machines.coremachines.FetchStoreInfoRequest
	2,  // 15: rpc.proto.machines.coremachines.CoreMachineService.FetchEnv:output_type -> rpc.proto.machines.coremachines.FetchEnvResponse
	6,  // 16: rpc.proto.machines.coremachines.CoreMachineService.FetchPlugin:output_type -> rpc.proto.machines.coremachines.FetchPluginResponse
	8,  // 17: rpc.proto.machines.coremachines.CoreMachineService.FetchPlugins:output_type -> rpc.proto.machines.coremachines.FetchPluginsResponse
	10, // 18: rpc.proto.machines.coremachines.CoreMachineService.FetchLatestPluginRelease:output_type -> rpc.proto.machines.coremachines.FetchLatestPluginReleaseResponse
	12, // 19: rpc.proto.machines.coremachines.CoreMachineService.FetchLatestCoreRelease:output_type -> rpc.proto.machines.coremachines.FetchLatestCoreReleaseResponse
	16, // 20: rpc.proto.machines.coremachines.CoreMachineService.FetchPluginByPRId:output_type -> rpc.proto.machines.coremachines.FetchPluginByPRIdResponse
	14, // 21: rpc.proto.machines.coremachines.CoreMachineService.FetchStoreInfo:output_type -> rpc.proto.machines.coremachines.FetchStoreInfoResponse
	15, // [15:22] is the sub-list for method output_type
	8,  // [8:15] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_init() }
func file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_init() {
	if File_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreVersion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchEnvRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchEnvResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Plugin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PluginRelease); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchPluginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchPluginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchPluginsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchPluginsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchLatestPluginReleaseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchLatestPluginReleaseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchLatestCoreReleaseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchLatestCoreReleaseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchStoreInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchStoreInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchPluginByPRIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchPluginByPRIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_goTypes,
		DependencyIndexes: file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_depIdxs,
		MessageInfos:      file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes,
	}.Build()
	File_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto = out.File
	file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_rawDesc = nil
	file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_goTypes = nil
	file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_depIdxs = nil
}
