// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.21.12
// source: rpc/proto/machines/coremachines/core_machine.v0.0.1.service.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FetchEnvRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FetchEnvRequest) Reset() {
	*x = FetchEnvRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchEnvRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchEnvRequest) ProtoMessage() {}

func (x *FetchEnvRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchEnvRequest.ProtoReflect.Descriptor instead.
func (*FetchEnvRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_rawDescGZIP(), []int{0}
}

type FetchEnvResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	S3AccessKey string `protobuf:"bytes,1,opt,name=s3_access_key,json=s3AccessKey,proto3" json:"s3_access_key,omitempty"`
	S3SecretKey string `protobuf:"bytes,2,opt,name=s3_secret_key,json=s3SecretKey,proto3" json:"s3_secret_key,omitempty"`
}

func (x *FetchEnvResponse) Reset() {
	*x = FetchEnvResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchEnvResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchEnvResponse) ProtoMessage() {}

func (x *FetchEnvResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchEnvResponse.ProtoReflect.Descriptor instead.
func (*FetchEnvResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_rawDescGZIP(), []int{1}
}

func (x *FetchEnvResponse) GetS3AccessKey() string {
	if x != nil {
		return x.S3AccessKey
	}
	return ""
}

func (x *FetchEnvResponse) GetS3SecretKey() string {
	if x != nil {
		return x.S3SecretKey
	}
	return ""
}

type Plugin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PluginId int32  `protobuf:"varint,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Package  string `protobuf:"bytes,3,opt,name=package,proto3" json:"package,omitempty"`
}

func (x *Plugin) Reset() {
	*x = Plugin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Plugin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plugin) ProtoMessage() {}

func (x *Plugin) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plugin.ProtoReflect.Descriptor instead.
func (*Plugin) Descriptor() ([]byte, []int) {
	return file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_rawDescGZIP(), []int{2}
}

func (x *Plugin) GetPluginId() int32 {
	if x != nil {
		return x.PluginId
	}
	return 0
}

func (x *Plugin) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Plugin) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

type PluginRelease struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PluginReleaseId int32  `protobuf:"varint,1,opt,name=plugin_release_id,json=pluginReleaseId,proto3" json:"plugin_release_id,omitempty"`
	Major           int32  `protobuf:"varint,2,opt,name=major,proto3" json:"major,omitempty"`
	Minor           int32  `protobuf:"varint,3,opt,name=minor,proto3" json:"minor,omitempty"`
	Patch           int32  `protobuf:"varint,4,opt,name=patch,proto3" json:"patch,omitempty"`
	ZipFileUrl      string `protobuf:"bytes,5,opt,name=zip_file_url,json=zipFileUrl,proto3" json:"zip_file_url,omitempty"`
}

func (x *PluginRelease) Reset() {
	*x = PluginRelease{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PluginRelease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginRelease) ProtoMessage() {}

func (x *PluginRelease) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginRelease.ProtoReflect.Descriptor instead.
func (*PluginRelease) Descriptor() ([]byte, []int) {
	return file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_rawDescGZIP(), []int{3}
}

func (x *PluginRelease) GetPluginReleaseId() int32 {
	if x != nil {
		return x.PluginReleaseId
	}
	return 0
}

func (x *PluginRelease) GetMajor() int32 {
	if x != nil {
		return x.Major
	}
	return 0
}

func (x *PluginRelease) GetMinor() int32 {
	if x != nil {
		return x.Minor
	}
	return 0
}

func (x *PluginRelease) GetPatch() int32 {
	if x != nil {
		return x.Patch
	}
	return 0
}

func (x *PluginRelease) GetZipFileUrl() string {
	if x != nil {
		return x.ZipFileUrl
	}
	return ""
}

type FetchPluginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PluginId int32 `protobuf:"varint,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
}

func (x *FetchPluginRequest) Reset() {
	*x = FetchPluginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchPluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchPluginRequest) ProtoMessage() {}

func (x *FetchPluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchPluginRequest.ProtoReflect.Descriptor instead.
func (*FetchPluginRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_rawDescGZIP(), []int{4}
}

func (x *FetchPluginRequest) GetPluginId() int32 {
	if x != nil {
		return x.PluginId
	}
	return 0
}

type FetchPluginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Plugin   *Plugin          `protobuf:"bytes,1,opt,name=plugin,proto3" json:"plugin,omitempty"`
	Releases []*PluginRelease `protobuf:"bytes,2,rep,name=releases,proto3" json:"releases,omitempty"`
}

func (x *FetchPluginResponse) Reset() {
	*x = FetchPluginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchPluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchPluginResponse) ProtoMessage() {}

func (x *FetchPluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchPluginResponse.ProtoReflect.Descriptor instead.
func (*FetchPluginResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_rawDescGZIP(), []int{5}
}

func (x *FetchPluginResponse) GetPlugin() *Plugin {
	if x != nil {
		return x.Plugin
	}
	return nil
}

func (x *FetchPluginResponse) GetReleases() []*PluginRelease {
	if x != nil {
		return x.Releases
	}
	return nil
}

type FetchPluginsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FetchPluginsRequest) Reset() {
	*x = FetchPluginsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchPluginsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchPluginsRequest) ProtoMessage() {}

func (x *FetchPluginsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchPluginsRequest.ProtoReflect.Descriptor instead.
func (*FetchPluginsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_rawDescGZIP(), []int{6}
}

type FetchPluginsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Plugins []*Plugin `protobuf:"bytes,1,rep,name=plugins,proto3" json:"plugins,omitempty"`
}

func (x *FetchPluginsResponse) Reset() {
	*x = FetchPluginsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchPluginsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchPluginsResponse) ProtoMessage() {}

func (x *FetchPluginsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchPluginsResponse.ProtoReflect.Descriptor instead.
func (*FetchPluginsResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_rawDescGZIP(), []int{7}
}

func (x *FetchPluginsResponse) GetPlugins() []*Plugin {
	if x != nil {
		return x.Plugins
	}
	return nil
}

type FetchLatestCoreReleaseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FetchLatestCoreReleaseRequest) Reset() {
	*x = FetchLatestCoreReleaseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchLatestCoreReleaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchLatestCoreReleaseRequest) ProtoMessage() {}

func (x *FetchLatestCoreReleaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchLatestCoreReleaseRequest.ProtoReflect.Descriptor instead.
func (*FetchLatestCoreReleaseRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_rawDescGZIP(), []int{8}
}

type FetchLatestCoreReleaseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CoreReleaseId  int32  `protobuf:"varint,1,opt,name=core_release_id,json=coreReleaseId,proto3" json:"core_release_id,omitempty"`
	Major          int32  `protobuf:"varint,2,opt,name=major,proto3" json:"major,omitempty"`
	Minor          int32  `protobuf:"varint,3,opt,name=minor,proto3" json:"minor,omitempty"`
	Patch          int32  `protobuf:"varint,4,opt,name=patch,proto3" json:"patch,omitempty"`
	CoreZipFileUrl string `protobuf:"bytes,5,opt,name=core_zip_file_url,json=coreZipFileUrl,proto3" json:"core_zip_file_url,omitempty"`
	ArchBinFileUrl string `protobuf:"bytes,6,opt,name=arch_bin_file_url,json=archBinFileUrl,proto3" json:"arch_bin_file_url,omitempty"`
}

func (x *FetchLatestCoreReleaseResponse) Reset() {
	*x = FetchLatestCoreReleaseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchLatestCoreReleaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchLatestCoreReleaseResponse) ProtoMessage() {}

func (x *FetchLatestCoreReleaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchLatestCoreReleaseResponse.ProtoReflect.Descriptor instead.
func (*FetchLatestCoreReleaseResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_rawDescGZIP(), []int{9}
}

func (x *FetchLatestCoreReleaseResponse) GetCoreReleaseId() int32 {
	if x != nil {
		return x.CoreReleaseId
	}
	return 0
}

func (x *FetchLatestCoreReleaseResponse) GetMajor() int32 {
	if x != nil {
		return x.Major
	}
	return 0
}

func (x *FetchLatestCoreReleaseResponse) GetMinor() int32 {
	if x != nil {
		return x.Minor
	}
	return 0
}

func (x *FetchLatestCoreReleaseResponse) GetPatch() int32 {
	if x != nil {
		return x.Patch
	}
	return 0
}

func (x *FetchLatestCoreReleaseResponse) GetCoreZipFileUrl() string {
	if x != nil {
		return x.CoreZipFileUrl
	}
	return ""
}

func (x *FetchLatestCoreReleaseResponse) GetArchBinFileUrl() string {
	if x != nil {
		return x.ArchBinFileUrl
	}
	return ""
}

var File_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto protoreflect.FileDescriptor

var file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_rawDesc = []byte{
	0x0a, 0x41, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x61, 0x63, 0x68,
	0x69, 0x6e, 0x65, 0x73, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65,
	0x73, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x2e, 0x76,
	0x30, 0x2e, 0x30, 0x2e, 0x31, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x1f, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d,
	0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x73, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x6d, 0x61, 0x63, 0x68,
	0x69, 0x6e, 0x65, 0x73, 0x22, 0x11, 0x0a, 0x0f, 0x46, 0x65, 0x74, 0x63, 0x68, 0x45, 0x6e, 0x76,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x5a, 0x0a, 0x10, 0x46, 0x65, 0x74, 0x63, 0x68,
	0x45, 0x6e, 0x76, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x0d, 0x73,
	0x33, 0x5f, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x73, 0x33, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4b, 0x65, 0x79, 0x12,
	0x22, 0x0a, 0x0d, 0x73, 0x33, 0x5f, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x5f, 0x6b, 0x65, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x33, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x4b, 0x65, 0x79, 0x22, 0x53, 0x0a, 0x06, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x12, 0x1b, 0x0a,
	0x09, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x22, 0x9f, 0x01, 0x0a, 0x0d, 0x50, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x11, 0x70, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x5f, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x6c,
	0x65, 0x61, 0x73, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x61, 0x6a, 0x6f, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x61, 0x6a, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05,
	0x6d, 0x69, 0x6e, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x69, 0x6e,
	0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x61, 0x74, 0x63, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x70, 0x61, 0x74, 0x63, 0x68, 0x12, 0x20, 0x0a, 0x0c, 0x7a, 0x69, 0x70, 0x5f,
	0x66, 0x69, 0x6c, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x7a, 0x69, 0x70, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x72, 0x6c, 0x22, 0x31, 0x0a, 0x12, 0x46, 0x65,
	0x74, 0x63, 0x68, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x49, 0x64, 0x22, 0xa2, 0x01,
	0x0a, 0x13, 0x46, 0x65, 0x74, 0x63, 0x68, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x06, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x73, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x6d,
	0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x73, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x52, 0x06,
	0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x12, 0x4a, 0x0a, 0x08, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73,
	0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x73, 0x2e, 0x63, 0x6f,
	0x72, 0x65, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x73, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x52, 0x08, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73,
	0x65, 0x73, 0x22, 0x15, 0x0a, 0x13, 0x46, 0x65, 0x74, 0x63, 0x68, 0x50, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x59, 0x0a, 0x14, 0x46, 0x65, 0x74,
	0x63, 0x68, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x41, 0x0a, 0x07, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x27, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d,
	0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x73, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x6d, 0x61, 0x63, 0x68,
	0x69, 0x6e, 0x65, 0x73, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x52, 0x07, 0x70, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x73, 0x22, 0x1f, 0x0a, 0x1d, 0x46, 0x65, 0x74, 0x63, 0x68, 0x4c, 0x61, 0x74,
	0x65, 0x73, 0x74, 0x43, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xe0, 0x01, 0x0a, 0x1e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x4c,
	0x61, 0x74, 0x65, 0x73, 0x74, 0x43, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x0f, 0x63, 0x6f, 0x72, 0x65,
	0x5f, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0d, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x6d, 0x61, 0x6a, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x6d, 0x61, 0x6a, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x69, 0x6e, 0x6f, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x69, 0x6e, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05,
	0x70, 0x61, 0x74, 0x63, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x70, 0x61, 0x74,
	0x63, 0x68, 0x12, 0x29, 0x0a, 0x11, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x7a, 0x69, 0x70, 0x5f, 0x66,
	0x69, 0x6c, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63,
	0x6f, 0x72, 0x65, 0x5a, 0x69, 0x70, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x29, 0x0a,
	0x11, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x62, 0x69, 0x6e, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x75,
	0x72, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x61, 0x72, 0x63, 0x68, 0x42, 0x69,
	0x6e, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x72, 0x6c, 0x32, 0x98, 0x04, 0x0a, 0x12, 0x43, 0x6f, 0x72,
	0x65, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x6f, 0x0a, 0x08, 0x46, 0x65, 0x74, 0x63, 0x68, 0x45, 0x6e, 0x76, 0x12, 0x30, 0x2e, 0x72, 0x70,
	0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x73,
	0x2e, 0x63, 0x6f, 0x72, 0x65, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x73, 0x2e, 0x46, 0x65,
	0x74, 0x63, 0x68, 0x45, 0x6e, 0x76, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x31, 0x2e,
	0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e,
	0x65, 0x73, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x73, 0x2e,
	0x46, 0x65, 0x74, 0x63, 0x68, 0x45, 0x6e, 0x76, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x78, 0x0a, 0x0b, 0x46, 0x65, 0x74, 0x63, 0x68, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x12,
	0x33, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x61, 0x63, 0x68,
	0x69, 0x6e, 0x65, 0x73, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65,
	0x73, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x34, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x73, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x6d, 0x61,
	0x63, 0x68, 0x69, 0x6e, 0x65, 0x73, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x50, 0x6c, 0x75, 0x67,
	0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x7b, 0x0a, 0x0c, 0x46, 0x65,
	0x74, 0x63, 0x68, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x12, 0x34, 0x2e, 0x72, 0x70, 0x63,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x73, 0x2e,
	0x63, 0x6f, 0x72, 0x65, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x73, 0x2e, 0x46, 0x65, 0x74,
	0x63, 0x68, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x35, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x61, 0x63,
	0x68, 0x69, 0x6e, 0x65, 0x73, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e,
	0x65, 0x73, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x99, 0x01, 0x0a, 0x16, 0x46, 0x65, 0x74, 0x63,
	0x68, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x43, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x6c, 0x65, 0x61,
	0x73, 0x65, 0x12, 0x3e, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d,
	0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x73, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x6d, 0x61, 0x63, 0x68,
	0x69, 0x6e, 0x65, 0x73, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74,
	0x43, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x3f, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d,
	0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x73, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x6d, 0x61, 0x63, 0x68,
	0x69, 0x6e, 0x65, 0x73, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74,
	0x43, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x22, 0x5a, 0x20, 0x72, 0x70, 0x63, 0x2f, 0x6d, 0x61, 0x63, 0x68, 0x69,
	0x6e, 0x65, 0x73, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x73,
	0x2f, 0x76, 0x30, 0x5f, 0x30, 0x5f, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_rawDescOnce sync.Once
	file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_rawDescData = file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_rawDesc
)

func file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_rawDescGZIP() []byte {
	file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_rawDescOnce.Do(func() {
		file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_rawDescData)
	})
	return file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_rawDescData
}

var file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_goTypes = []interface{}{
	(*FetchEnvRequest)(nil),                // 0: rpc.proto.machines.coremachines.FetchEnvRequest
	(*FetchEnvResponse)(nil),               // 1: rpc.proto.machines.coremachines.FetchEnvResponse
	(*Plugin)(nil),                         // 2: rpc.proto.machines.coremachines.Plugin
	(*PluginRelease)(nil),                  // 3: rpc.proto.machines.coremachines.PluginRelease
	(*FetchPluginRequest)(nil),             // 4: rpc.proto.machines.coremachines.FetchPluginRequest
	(*FetchPluginResponse)(nil),            // 5: rpc.proto.machines.coremachines.FetchPluginResponse
	(*FetchPluginsRequest)(nil),            // 6: rpc.proto.machines.coremachines.FetchPluginsRequest
	(*FetchPluginsResponse)(nil),           // 7: rpc.proto.machines.coremachines.FetchPluginsResponse
	(*FetchLatestCoreReleaseRequest)(nil),  // 8: rpc.proto.machines.coremachines.FetchLatestCoreReleaseRequest
	(*FetchLatestCoreReleaseResponse)(nil), // 9: rpc.proto.machines.coremachines.FetchLatestCoreReleaseResponse
}
var file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_depIdxs = []int32{
	2, // 0: rpc.proto.machines.coremachines.FetchPluginResponse.plugin:type_name -> rpc.proto.machines.coremachines.Plugin
	3, // 1: rpc.proto.machines.coremachines.FetchPluginResponse.releases:type_name -> rpc.proto.machines.coremachines.PluginRelease
	2, // 2: rpc.proto.machines.coremachines.FetchPluginsResponse.plugins:type_name -> rpc.proto.machines.coremachines.Plugin
	0, // 3: rpc.proto.machines.coremachines.CoreMachineService.FetchEnv:input_type -> rpc.proto.machines.coremachines.FetchEnvRequest
	4, // 4: rpc.proto.machines.coremachines.CoreMachineService.FetchPlugin:input_type -> rpc.proto.machines.coremachines.FetchPluginRequest
	6, // 5: rpc.proto.machines.coremachines.CoreMachineService.FetchPlugins:input_type -> rpc.proto.machines.coremachines.FetchPluginsRequest
	8, // 6: rpc.proto.machines.coremachines.CoreMachineService.FetchLatestCoreRelease:input_type -> rpc.proto.machines.coremachines.FetchLatestCoreReleaseRequest
	1, // 7: rpc.proto.machines.coremachines.CoreMachineService.FetchEnv:output_type -> rpc.proto.machines.coremachines.FetchEnvResponse
	5, // 8: rpc.proto.machines.coremachines.CoreMachineService.FetchPlugin:output_type -> rpc.proto.machines.coremachines.FetchPluginResponse
	7, // 9: rpc.proto.machines.coremachines.CoreMachineService.FetchPlugins:output_type -> rpc.proto.machines.coremachines.FetchPluginsResponse
	9, // 10: rpc.proto.machines.coremachines.CoreMachineService.FetchLatestCoreRelease:output_type -> rpc.proto.machines.coremachines.FetchLatestCoreReleaseResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_init() }
func file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_init() {
	if File_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchEnvRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchEnvResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Plugin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PluginRelease); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchPluginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchPluginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchPluginsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchPluginsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchLatestCoreReleaseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchLatestCoreReleaseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_goTypes,
		DependencyIndexes: file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_depIdxs,
		MessageInfos:      file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_msgTypes,
	}.Build()
	File_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto = out.File
	file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_rawDesc = nil
	file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_goTypes = nil
	file_rpc_proto_machines_coremachines_core_machine_v0_0_1_service_proto_depIdxs = nil
}
